### ISSUE TITLE
Crashes Bumblezone in Fabric 1.21.1

### ISSUE THREAD

**Issue by TelepathicGrunt** [Discusser/TooManyEntities#5]
A player made a bug report that this mod crashes Bumblezone 

https://github.com/TelepathicGrunt/Bumblezone/issues/455

I don’t agree with your mod’s entire concept but even then, here’s a bug report to help you out. More info and crashlog in the link above

**Comment by Discusser** [comment]
This issue shouldn't occur on the latest version of my mod. They're using v1.0.1 while the latest for 1.21.1 is v1.1.2. If the issue still occurs on the latest version I'll work to fix it.

By the way, I understand that hiding piglin brutes or other hostile entities is not a good idea, which is why you can choose to limit the count of only certain entities. Honestly when making the mod my idea was just to hide excess animals in farms (cows, chicken, sheep, pigs..)
